### ISSUE TITLE
no "12" key in status

### ISSUE THREAD

**Issue by okami-1** [DenisCarriere/gopro#8]
I don't have a key "12" in status.

status_screen = status_screen[self.status_raw.get('12')] 
KeyError: None

output of the http://10.5.5.9/gp/gpControl/status/
{"status":{
"1":1,"2":2,"3":0,"4":0,"6":0,"8":0,"9":0,"10":0,"11":0,"13":0,"14":0,"15":0,"16":0,"17":1,"19":0,"20":0,"21":0,"22":0,"23":0,"24":0,"26":0,"27":0,"28":2,"29":"","30":"","31":1,"32":0,"33":0,"34":2331,"35":3906,"36":0,"37":0,"38":0,"39":0,"40":"%0F%06%18%14%1F%17","41":0,"42":0,"43":0,"44":0,"45":0,"46":1,"47":1,"48":1,"49":0,"54":15508576,"55":1,"56":4,"57":856028,"58":0,"59":0},
"settings": {"1":0,"2":9,"3":5,"4":0,"5":0,"6":1,"7":1,"8":0,"9":0,"10":0,"11":0,"12":0,"13":1,"14":0,"15":4,"16":0,"17":0,"18":0,"19":0,"20":0,"21":0,"22":0,"23":0,"24":0,"25":0,"26":4,"27":0,"28":0,"29":5,"30":0,"31":0,"32":0,"33":0,"34":0,"35":0,"36":0,"37":0,"38":0,"39":4,"40":0,"41":13,"42":8,"43":0,"44":8,"45":8,"46":0,"47":0,"48":0,"49":0,"50":1,"51":1,"52":1,"53":0,"54":0,"55":2,"56":0,"57":0,"58":1,"59":0,"60":8,"61":1,"62":700000,"63":1,"64":1,"65":0,"66":0,"67":0,"68":0,"69":0,"70":0,"71":0,"72":1}}

**Comment by DenisCarriere** [comment]
Which GoPro are you using? Hero 4 or GoPro 3?

**Comment by okami-1** [comment]
GoPro Hero4 Black Edition

**Comment by mshukla95** [comment]
I'm having the same problem as well with a Hero4 Silver

>>> camera = GoPro()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gopro/GoPro.py", line 23, in __init__
    self.status_connection
  File "gopro/GoPro.py", line 117, in status_connection
    self.status['connection'] = self.connection
  File "gopro/GoPro.py", line 59, in status
    self.status_screen
  File "gopro/GoPro.py", line 129, in status_screen
    status_screen = status_screen[self.status_raw.get('12')] 
KeyError: None
 
Do we need to change 12 to something else?

**Comment by mshukla95** [comment]
I also tried accessing the livestream from this URL:

http://10.5.5.9/gp/gpExec?p1=gpStreamA9&c1=restart

But that also didn't work. Did they change these settings so we can't root the cameras like this?

**Comment by DenisCarriere** [comment]
It does seem like they are preventing this from happening. I haven't tried
to access it in a while, maybe a firmware update changed the URL link

**Comment by mshukla95** [comment]
I just found this repo. I don't know if it can give any insights into this issue. https://github.com/sinkers/golapse

**Comment by DenisCarriere** [comment]
It's a great example, however it's for the gopro3, the newer models have a
different api.

**Comment by KonradIT** [comment]
Hi, there is no 12 in status. 12 in setting is the GoPro Color Protune profile (https://github.com/KonradIT/goprowifihack/blob/master/HERO4/CameraStatus.md)
